name: GPT Code Update

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay cambios en la rama main

  schedule:
    - cron: '0 0 * * *'  # Se ejecuta automáticamente todos los días a medianoche (UTC)

  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  update_code:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Simular actualización con GPT
        run: |
          echo "Este es un cambio generado por GPT" > client/public/info.txt

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Hacer commit y push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add .
          git commit -m "Actualización automática con GPT" || echo "No hay cambios para commit"
          git push https://x-access-token:${GH_PAT}@github.com/Charly998/foro-anonimo.git main || echo "No se pudo hacer push"

