name: Actualizar Código con GPT

on:
  workflow_dispatch:  # Se ejecuta manualmente desde GitHub
  schedule:
    - cron: '0 12 * * *'  # Se ejecuta todos los días a las 12 PM UTC

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Clonar repositorio
        uses: actions/checkout@v3

      - name: 🧠 Instalar OpenAI CLI
        run: pip install openai

      - name: 📂 Ejecutar script de actualización
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/update_with_gpt.py

      - name: 📤 Subir cambios al repositorio
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🤖 Actualización automática con GPT" || echo "Sin cambios para hacer commit"
          git push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

